language: scala

sudo: false

scala:
  - "2.12.8"

jdk:
  - oraclejdk8

# build all PRs and only master branch and branches starting with either
# 'deploy-*', 'deploy/*', 'ci-*' or 'ci/*'
branches:
  only:
    - master
    - /^(?i:deploy)(-|\/).*$/
    - /^(?i:ci)(-|\/).*$/

# cache local ivy cache, but delete properties and lock files beforehand
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - data

# if build is a pull request and origin branch starts with doc/ skip the build (successfully)
before_install:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" && "$TRAVIS_PULL_REQUEST_BRANCH" == doc/* ]]; then exit 0; fi

before_script:
  - mkdir -p data
  - "[ -f data/test.csv ] || curl -o data/test.csv https://gist.githubusercontent.com/CodeLionX/2bc7f6145dd21bc9c1ebcb94a922d428/raw/0ab1f828a370a2795f125ee19da1610b1054cf9e/tests.csv"

# build script (sbt test and sbt run sampleapp.Main)
script:
  # exclude tests tagged with DataTest from the test run
  - sbt ++$TRAVIS_SCALA_VERSION \
      coverage \
      'testOnly -- -l "com.github.codelionx.dodo.testing.tags.DataTests"' \
      coverageReport \
      coverageAggregate \
      codacyCoverage
  - sbt ++$TRAVIS_SCALA_VERSION -Dcom.github.codelionx.dodo.input-file=data/test.csv run